# frozen_string_literal: true

require_relative './fsp_harvester/version'
require 'json/ld'
require 'json/ld/preloaded'
require 'json'
require 'linkheaders/processor'
require 'addressable'
require 'tempfile'
require 'xmlsimple'
require 'nokogiri'
require 'parseconfig'
require 'rest-client'
require 'cgi'
require 'digest'
require 'open3'
require 'metainspector'
require 'rdf/xsd'
require_relative './metadata_object'
require_relative './constants'
require_relative './web_utils'
require_relative './signposting_tests'
require_relative './metadata_harvester'
require_relative './fsp_harvester'
require_relative './harvester_utils'
require_relative './harvester_brute'
require_relative './external_tools'
require_relative './metadata_parser'